#include "../include/manual_rules.h"
#include <string.h>

char* manual_rules(char *miss) {
    // int score = 0;

    struct Correction {
        char *wrong;
        char *right;
    };

    // if (strcmp(miss, "alot") == 0 && strcmp(line, "a lot") == 0) return 100;
    // if (strcmp(miss, "alright") == 0 && strcmp(line, "all right") == 0) return 100;
    // if (strcmp(miss, "Dravadian") == 0 && strcmp(line, "Dravidian") == 0) return 100;
    // if (strcmp(miss, "Enlish") == 0 && strcmp(line, "English, enlist") == 0) return 100;
    // if (strcmp(miss, "Europian") == 0 && strcmp(line, "European") == 0) return 100;
    // if (strcmp(miss, "Europians") == 0 && strcmp(line, "Europeans") == 0) return 100;
    // if (strcmp(miss, "Eurpean") == 0 && strcmp(line, "European") == 0) return 100;
    // if (strcmp(miss, "Eurpoean") == 0 && strcmp(line, "European") == 0) return 100;
    // if (strcmp(miss, "Farenheit") == 0 && strcmp(line, "Fahrenheit") == 0) return 100;
    // if (strcmp(miss, "Febuary") == 0 && strcmp(line, "February") == 0) return 100;
    // if (strcmp(miss, "Feburary") == 0 && strcmp(line, "February") == 0) return 100;
    // if (strcmp(miss, "Flemmish") == 0 && strcmp(line, "Flemish") == 0) return 100;
    // if (strcmp(miss, "Formalhaut") == 0 && strcmp(line, "Fomalhaut") == 0) return 100;
    // if (strcmp(miss, "Foundland") == 0 && strcmp(line, "Newfoundland") == 0) return 100;
    // if (strcmp(miss, "Fransiscan") == 0 && strcmp(line, "Franciscan") == 0) return 100;
    // if (strcmp(miss, "Fransiscans") == 0 && strcmp(line, "Franciscans") == 0) return 100;
    // if (strcmp(miss, "Galations") == 0 && strcmp(line, "Galatians") == 0) return 100;
    // if (strcmp(miss, "Gameboy") == 0 && strcmp(line, "Game Boy") == 0) return 100;
    // if (strcmp(miss, "Ghandi") == 0 && strcmp(line, "Gandhi") == 0) return 100;
    // if (strcmp(miss, "Godounov") == 0 && strcmp(line, "Godunov") == 0) return 100;
    // if (strcmp(miss, "Gothenberg") == 0 && strcmp(line, "Gothenburg") == 0) return 100;
    // if (strcmp(miss, "Gottleib") == 0 && strcmp(line, "Gottlieb") == 0) return 100;
    // if (strcmp(miss, "Guaduloupe") == 0 && strcmp(line, "Guadalupe, Guadeloupe") == 0) return 100;
    // if (strcmp(miss, "Guadulupe") == 0 && strcmp(line, "Guadalupe, Guadeloupe") == 0) return 100;
    // if (strcmp(miss, "Guatamala") == 0 && strcmp(line, "Guatemala") == 0) return 100;
    // if (strcmp(miss, "Guatamalan") == 0 && strcmp(line, "Guatemalan") == 0) return 100;
    // if (strcmp(miss, "Guilia") == 0 && strcmp(line, "Giulia") == 0) return 100;
    // if (strcmp(miss, "Guilio") == 0 && strcmp(line, "Giulio") == 0) return 100;
    // if (strcmp(miss, "Guiness") == 0 && strcmp(line, "Guinness") == 0) return 100;
    // if (strcmp(miss, "Guiseppe") == 0 && strcmp(line, "Giuseppe") == 0) return 100;
    // if (strcmp(miss, "Habsbourg") == 0 && strcmp(line, "Habsburg") == 0) return 100;
    // if (strcmp(miss, "Hatian") == 0 && strcmp(line, "Haitian") == 0) return 100;
    // if (strcmp(miss, "Heidelburg") == 0 && strcmp(line, "Heidelberg") == 0) return 100;
    // if (strcmp(miss, "Ihaca") == 0 && strcmp(line, "Ithaca") == 0) return 100;
    // if (strcmp(miss, "Israelies") == 0 && strcmp(line, "Israelis") == 0) return 100;
    // if (strcmp(miss, "Janurary") == 0 && strcmp(line, "January") == 0) return 100;
    // if (strcmp(miss, "Januray") == 0 && strcmp(line, "January") == 0) return 100;
    // if (strcmp(miss, "Japanes") == 0 && strcmp(line, "Japanese") == 0) return 100;
    // if (strcmp(miss, "Johanine") == 0 && strcmp(line, "Johannine") == 0) return 100;
    // if (strcmp(miss, "Jospeh") == 0 && strcmp(line, "Joseph") == 0) return 100;
    // if (strcmp(miss, "Juadaism") == 0 && strcmp(line, "Judaism") == 0) return 100;
    // if (strcmp(miss, "Juadism") == 0 && strcmp(line, "Judaism") == 0) return 100;
    // if (strcmp(miss, "Lybia") == 0 && strcmp(line, "Libya") == 0) return 100;
    // if (strcmp(miss, "Malcom") == 0 && strcmp(line, "Malcolm") == 0) return 100;
    // if (strcmp(miss, "Massachussets") == 0 && strcmp(line, "Massachusetts") == 0) return 100;
    // if (strcmp(miss, "Massachussetts") == 0 && strcmp(line, "Massachusetts") == 0) return 100;
    // if (strcmp(miss, "Mediteranean") == 0 && strcmp(line, "Mediterranean") == 0) return 100;
    // if (strcmp(miss, "Michagan") == 0 && strcmp(line, "Michigan") == 0) return 100;
    // if (strcmp(miss, "Misouri") == 0 && strcmp(line, "Missouri") == 0) return 100;
    // if (strcmp(miss, "Missisipi") == 0 && strcmp(line, "Mississippi") == 0) return 100;
    // if (strcmp(miss, "Missisippi") == 0 && strcmp(line, "Mississippi") == 0) return 100;
    // if (strcmp(miss, "Monserrat") == 0 && strcmp(line, "Montserrat") == 0) return 100;
    // if (strcmp(miss, "Montnana") == 0 && strcmp(line, "Montana") == 0) return 100;
    // if (strcmp(miss, "Morisette") == 0 && strcmp(line, "Morissette") == 0) return 100;
    // if (strcmp(miss, "Morrisette") == 0 && strcmp(line, "Morissette") == 0) return 100;
    // if (strcmp(miss, "Mythraic") == 0 && strcmp(line, "Mithraic") == 0) return 100;
    // if (strcmp(miss, "Naploeon") == 0 && strcmp(line, "Napoleon") == 0) return 100;
    // if (strcmp(miss, "Napolean") == 0 && strcmp(line, "Napoleon") == 0) return 100;
    // if (strcmp(miss, "Napoleonian") == 0 && strcmp(line, "Napoleonic") == 0) return 100;
    // if (strcmp(miss, "Nazereth") == 0 && strcmp(line, "Nazareth") == 0) return 100;
    // if (strcmp(miss, "Novermber") == 0 && strcmp(line, "November") == 0) return 100;
    // if (strcmp(miss, "Nullabour") == 0 && strcmp(line, "Nullarbor") == 0) return 100;
    // if (strcmp(miss, "Nuremburg") == 0 && strcmp(line, "Nuremberg") == 0) return 100;
    // if (strcmp(miss, "Palistian") == 0 && strcmp(line, "Palestinian") == 0) return 100;
    // if (strcmp(miss, "Palistinian") == 0 && strcmp(line, "Palestinian") == 0) return 100;
    // if (strcmp(miss, "Palistinians") == 0 && strcmp(line, "Palestinians") == 0) return 100;
    // if (strcmp(miss, "Papanicalou") == 0 && strcmp(line, "Papanicolaou") == 0) return 100;
    // if (strcmp(miss, "Peloponnes") == 0 && strcmp(line, "Peloponnesus") == 0) return 100;
    // if (strcmp(miss, "Pennyslvania") == 0 && strcmp(line, "Pennsylvania") == 0) return 100;
    // if (strcmp(miss, "Pharoah") == 0 && strcmp(line, "Pharaoh") == 0) return 100;
    // if (strcmp(miss, "Philipines") == 0 && strcmp(line, "Philippines") == 0) return 100;
    // if (strcmp(miss, "Phillipine") == 0 && strcmp(line, "Philippine") == 0) return 100;
    // if (strcmp(miss, "Phillipines") == 0 && strcmp(line, "Philippines") == 0) return 100;
    // if (strcmp(miss, "Phillippines") == 0 && strcmp(line, "Philippines") == 0) return 100;
    // if (strcmp(miss, "Phonecian") == 0 && strcmp(line, "Phoenecian") == 0) return 100;
    // if (strcmp(miss, "Portugese") == 0 && strcmp(line, "Portuguese") == 0) return 100;
    // if (strcmp(miss, "Postdam") == 0 && strcmp(line, "Potsdam") == 0) return 100;
    // if (strcmp(miss, "Premonasterians") == 0 && strcmp(line, "Premonstratensians") == 0) return 100;
    // if (strcmp(miss, "Pucini") == 0 && strcmp(line, "Puccini") == 0) return 100;
    // if (strcmp(miss, "Puertorrican") == 0 && strcmp(line, "Puerto Rican") == 0) return 100;
    // if (strcmp(miss, "Puertorricans") == 0 && strcmp(line, "Puerto Ricans") == 0) return 100;
    // if (strcmp(miss, "Queenland") == 0 && strcmp(line, "Queensland") == 0) return 100;
    // if (strcmp(miss, "Rockerfeller") == 0 && strcmp(line, "Rockefeller") == 0) return 100;
    // if (strcmp(miss, "Russion") == 0 && strcmp(line, "Russian") == 0) return 100;
    // if (strcmp(miss, "Sacremento") == 0 && strcmp(line, "Sacramento") == 0) return 100;
    // if (strcmp(miss, "Sanhedrim") == 0 && strcmp(line, "Sanhedrin") == 0) return 100;
    // if (strcmp(miss, "Saterday") == 0 && strcmp(line, "Saturday") == 0) return 100;
    // if (strcmp(miss, "Saterdays") == 0 && strcmp(line, "Saturdays") == 0) return 100;
    // if (strcmp(miss, "Sionist") == 0 && strcmp(line, "Zionist") == 0) return 100;
    // if (strcmp(miss, "Sionists") == 0 && strcmp(line, "Zionists") == 0) return 100;
    // if (strcmp(miss, "Sixtin") == 0 && strcmp(line, "Sistine") == 0) return 100;
    // if (strcmp(miss, "Skagerak") == 0 && strcmp(line, "Skagerrak") == 0) return 100;
    // if (strcmp(miss, "Tolkein") == 0 && strcmp(line, "Tolkien") == 0) return 100;
    // if (strcmp(miss, "Tuscon") == 0 && strcmp(line, "Tucson") == 0) return 100;
    // if (strcmp(miss, "Ukranian") == 0 && strcmp(line, "Ukrainian") == 0) return 100;
    // if (strcmp(miss, "Unites States") == 0 && strcmp(line, "United States") == 0) return 100;
    // if (strcmp(miss, "Yementite") == 0 && strcmp(line, "Yemenite, Yemeni") == 0) return 100;

    // struct Correction *dict = NULL;

    if (miss[0] == 'a') {
        static struct Correction dict[] = {
            {"abondon", "abandon"},
            {"abondoning", "abandoning"},
            {"abreviated", "abbreviated"},
            {"abondons", "abandons"},
            {"abreviation", "abbreviation"},
            {"absailing", "abseiling"},
            {"absense", "absence"},
            {"absolutly", "absolutely"},
            {"absorbsion", "absorption"},
            {"absorbtion", "absorption"},
            {"accension", "accession"},
            {"accension", "ascension"},
            {"acceptible", "acceptable"},
            {"accidant", "accident"},
            {"accomdate", "accommodate"},
            {"accoring", "according"},
            {"accquainted", "acquainted"},
            {"accredidation", "accreditation"},
            {"acedemic", "academic"},
            {"achiv", "achieve"},
            {"achive", "achieve, archive"},
            {"achived", "achieved, archived"},
            {"ackward", "awkward, backward"},
            {"activites", "activities"},
            {"adbandon", "abandon"},
            {"addmission", "admission"},
            {"addopted", "adopted"},
            {"addoptive", "adoptive"},
            {"addres", "address"},
            {"adequit", "adequate"},
            {"adhearing", "adhering"},
            {"adviceable", "advisable"},
            {"agressiev", "aggressive"},
            {"almsot", "almost"},
            {"alos", "also"},
            {"alot", "a lot, allot"},
            {"alreayd", "already"},
            {"altho", "although"},
            {"althought", "although"},
            {"alusion", "allusion, illusion"},
            {"alwasy", "always"},
            {"alwyas", "always"},
            {"amatuer", "amateur"},
            {"amature", "amateur, armature"},
            {"amercia", "america"},
            {"amke", "make"},
            {"amking", "making"},
            {"analagous", "analogous"},
            {"analitic", "analytic"},
            {"analize", "analyze"},
            {"anbd", "and"},
            {"ancestory", "ancestry"},
            {"andd", "and"},
            {"annointed", "anointed"},
            {"annointing", "anointing"},
            {"annuall", "annual"},
            {"anohter", "another"},
            {"anomoly", "anomaly"},
            {"ansalisation", "nasalisation"},
            {"ansalization", "nasalization"},
            {"ansestors", "ancestors"},
            {"anthromorphization", "anthropomorphization"},
            {"anuncement", "announcement"},
            {"anyother", "any other"},
            {"apenines", "apennines, apennines"},
            {"apparant", "apparent"},
            {"appartment", "apartment"},
            {"appartments", "apartments"},
            {"appealling", "appealing, appalling"},
            {"appearence", "appearance"},
            {"appearences", "appearances"},
            {"appenines", "apennines, apennines"},
            {"appereances", "appearances"},
            {"appologies", "apologies"},
            {"approachs", "approaches"},
            {"approproximate", "approximate"},
            {"approxamately", "approximately"},
            {"approximitely", "approximately"},
            {"aquainted", "acquainted"},
            {"aquire", "acquire"},
            {"aquitted", "acquitted"},
            {"archaoelogy", "archeology, archaeology"},
            {"archaology", "archeology, archaeology"},
            {"archeaologist", "archeologist, archaeologist"},
            {"archeaologists", "archeologists, archaeologists"},
            {"archiac", "archaic"},
            {"archimedian", "archimedean"},
            {"arguement", "argument"},
            {"arised", "arose"},
            {"armamant", "armament"},
            {"arogent", "arrogant"},
            {"aroud", "around"},
            {"arrengement", "arrangement"},
            {"arrengements", "arrangements"},
            {"artical", "article"},
            {"articel", "article"},
            {"asetic", "ascetic"},
            {"asfar", "as far"},
            {"aslo", "also"},
            {"asorbed", "absorbed"},
            {"assasined", "assassinated"},
            {"assemple", "assemble"},
            {"assertation", "assertion"},
            {"asside", "aside"},
            {"assisnate", "assassinate"},
            {"assistent", "assistant"},
            {"assit", "assist"},
            {"assymetric", "asymmetric"},
            {"asteriod", "asteroid"},
            {"asthetic", "aesthetic"},
            {"asthetical", "aesthetical"},
            {"asthetically", "aesthetically"},
            {"aswell", "as well"},
            {"atheistical", "atheistic"},
            {"athenean", "athenian"},
            {"atheneans", "athenians"},
            {"athiest", "atheist"},
            {"ateist", "atheist"},
            {"attaindre", "attainder, attained"},
            {"attemp", "attempt"},
            {"attemt", "attempt"},
            {"attendent", "attendant"},
            {"attendents", "attendants"},
            {"attened", "attended"},
            {"attitide", "attitude"},
            {"attributred", "attributed"},
            {"austrailia", "australia"},
            {"austrailian", "australian"},
            {"auther", "author"},
            {"authorative", "authoritative"},
            {"authorites", "authorities"},
            {"authorithy", "authority"},
            {"authoritiers", "authorities"},
            {"authoritive", "authoritative"},
            {"authour", "author"},
            {"autoctonous", "autochthonous"},
            {"automaticly", "automatically"},
            {"automonomous", "autonomous"},
            {"availabe", "available"},
            {"availabel", "available"},
            {"avalance", "avalanche"},
            {"avengence", "a vengeance"},
            {"awared", "aware, awarded"},
            {"awya", "away"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'b') {
        static struct Correction dict[] = {
            {"baceause", "because"},
            {"bakc", "back"},
            {"banannas", "bananas"},
            {"battelship", "battleship"},
            {"baout", "about, bout"},
            {"basicly", "basically"},
            {"bcak", "back"},
            {"beated", "beaten"},
            {"beaurocracy", "bureaucracy"},
            {"beaurocratic", "bureaucratic"},
            {"becamae", "became"},
            {"becames", "becomes, became"},
            {"becasue", "because"},
            {"becomeing", "becoming"},
            {"becomming", "becoming"},
            {"bedore", "before"},
            {"beeing", "being"},
            {"befoer", "before"},
            {"beggin", "begin, begging"},
            {"begining", "beginning"},
            {"behavour", "behavior"},
            {"beleive", "believe"},
            {"believ", "belief, believe"},
            {"beligum", "belgium"},
            {"belive", "believe"},
            {"belived", "believed, beloved"},
            {"belives", "believes, beliefs"},
            {"bergamont", "bergamot"},
            {"bernouilli", "bernoulli"},
            {"bigining", "beginning"},
            {"biginning", "beginning"},
            {"binominal", "binomial"},
            {"blaim", "blame"},
            {"blessure", "blessing"},
            {"blitzkreig", "blitzkrieg"},
            {"boaut", "bout, boat, about"},
            {"bonnano", "bonanno"},
            {"borke", "broke"},
            {"bouyancy", "buoyancy"},
            {"bouyant", "buoyant"},
            {"brasillian", "brazilian"},
            {"breif", "brief"},
            {"britian", "britain"},
            {"brittish", "british"},
            {"broacasted", "broadcast"},
            {"broady", "broadly"},
            {"buddah", "buddha"},
            {"buddist", "buddhist"},
            {"buring", "burying, burning, during, burin"},
            {"busines", "business"},
            {"busineses", "business, businesses"},
            {"busness", "business"},
            {"bussiness", "business"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'c') {
        static struct Correction dict[] = {
            {"caculater", "calculator"},
            {"cacuses", "caucuses"},
            {"cahracters", "characters"},
            {"calander", "calendar, colander"},
            {"calculater", "calculator"},
            {"calculs", "calculus"},
            {"calender", "calendar"},
            {"calenders", "calendars"},
            {"calulater", "calculator"},
            {"cambrige", "cambridge"},
            {"campagin", "campaign"},
            {"campain", "campaign"},
            {"campains", "campaigns"},
            {"cannister", "canister"},
            {"cannisters", "canisters"},
            {"cannotation", "connotation"},
            {"cannotations", "connotations"},
            {"caost", "coast"},
            {"capetown", "cape town"},
            {"captued", "captured"},
            {"capturd", "captured"},
            {"carachter", "character"},
            {"caracterized", "characterized"},
            {"carcas", "carcass, caracas"},
            {"careing", "caring"},
            {"carismatic", "charismatic"},
            {"carmalite", "carmelite"},
            {"carnagie", "carnegie"},
            {"carnagie ellon", "carnegie-mellon"},
            {"carnege", "carnage, carnegie"},
            {"carnige", "carnage, carnegie"},
            {"carnigie", "carnegie"},
            {"carnigie ellon", "carnegie-mellon"},
            {"carrers", "careers"},
            {"carribbean", "caribbean"},
            {"carribean", "caribbean"},
            {"carthagian", "carthaginian"},
            {"cartilidge", "cartilage"},
            {"cartrige", "cartridge"},
            {"casion", "caisson"},
            {"cassawory", "cassowary"},
            {"casue", "cause"},
            {"casued", "caused"},
            {"casues", "causes"},
            {"casuing", "causing"},
            {"casulaty", "casualty"},
            {"catagories", "categories"},
            {"catagorized", "categorized"},
            {"catagory", "category"},
            {"cataline", "catiline, catalina"},
            {"catapillers", "caterpillars"},
            {"cattleship", "battleship"},
            {"catholocism", "catholicism"},
            {"causalities", "casualties"},
            {"ceasar", "caesar"},
            {"celcius", "celsius"},
            {"cellpading", "cellpadding"},
            {"cementary", "cemetery"},
            {"cemetarey", "cemetery"},
            {"cemetary", "cemetery"},
            {"cencus", "census"},
            {"censur", "censor, censure"},
            {"centuties", "centuries"},
            {"centuty", "century"},
            {"ceratin", "certain, keratin"},
            {"cerimonies", "ceremonies"},
            {"cerimonious", "ceremonious"},
            {"certian", "certain"},
            {"cervial", "cervical, servile, serval"},
            {"champange", "champagne"},
            {"charactor", "character"},
            {"charactors", "characters"},
            {"charistics", "characteristics"},
            {"chasr", "chaser, chase"},
            {"chauffer", "chauffeur"},
            {"cheif", "chief"},
            {"cheifs", "chiefs"},
            {"childbird", "childbirth"},
            {"childen", "children"},
            {"choclate", "chocolate"},
            {"chracter", "character"},
            {"churchs", "churches"},
            {"cincinatti", "cincinnati"},
            {"cincinnatti", "cincinnati"},
            {"circumsicion", "circumcision"},
            {"circut", "circuit"},
            {"claer", "clear"},
            {"claerer", "clearer"},
            {"claimes", "claims"},
            {"clas", "class"},
            {"clera", "clear, sclera"},
            {"cmo", "com"},
            {"cmoputer", "computer"},
            {"cognizent", "cognizant"},
            {"coligue", "colleague"},
            {"collonies", "colonies"},
            {"colonizators", "colonizers"},
            {"colum", "column"},
            {"comander", "commander, commandeer"},
            {"combanations", "combinations"},
            {"combusion", "combustion"},
            {"comdemnation", "condemnation"},
            {"comision", "commission"},
            {"comisioned", "commissioned"},
            {"comisioning", "commissioning"},
            {"comisions", "commissions"},
            {"comite", "committee"},
            {"comited", "committed"},
            {"comitee", "committee"},
            {"comiting", "committing"},
            {"commandoes", "commandos"},
            {"comming", "coming"},
            {"comminication", "communication"},
            {"commongly", "commonly"},
            {"communiation", "communication"},
            {"communites", "communities"},
            {"compability", "compatibility"},
            {"comparision", "comparison"},
            {"comparisions", "comparisons"},
            {"comparitive", "comparative"},
            {"compatabilities", "compatibilities"},
            {"compatability", "compatibility"},
            {"compatable", "compatible"},
            {"competant", "competent"},
            {"competative", "competitive"},
            {"competion", "competition, completion"},
            {"competive", "competitive"},
            {"competiveness", "competitiveness"},
            {"compitent", "competent"},
            {"completelyl", "completely"},
            {"completetion", "completion"},
            {"completly", "completely"},
            {"complier", "compiler"},
            {"componant", "component"},
            {"comprimise", "compromise"},
            {"compulsary", "compulsory"},
            {"compulsery", "compulsory"},
            {"concider", "consider"},
            {"concidered", "considered"},
            {"concidering", "considering"},
            {"conciders", "considers"},
            {"condem", "condemn"},
            {"condemmed", "condemned"},
            {"condidtion", "condition"},
            {"condidtions", "conditions"},
            {"conditionsof", "conditions of"},
            {"confidental", "confidential"},
            {"confids", "confides"},
            {"configureable", "configurable"},
            {"confortable", "comfortable"},
            {"congradulations", "congratulations"},
            {"conneticut", "connecticut"},
            {"conquerd", "conquered"},
            {"conquerer", "conqueror"},
            {"conquerers", "conquerors"},
            {"conscent", "consent"},
            {"conscientous", "conscientious"},
            {"consdider", "consider"},
            {"consentrate", "concentrate"},
            {"consentrated", "concentrated"},
            {"consentrates", "concentrates"},
            {"consequentually", "consequently"},
            {"conserning", "concerning"},
            {"consiciousness", "consciousness"},
            {"considerd", "considered"},
            {"consideres", "considered"},
            {"consistant", "consistent"},
            {"consistantly", "consistently"},
            {"consolodate", "consolidate"},
            {"consolodated", "consolidated"},
            {"consonent", "consonant"},
            {"consonents", "consonants"},
            {"consorcium", "consortium"},
            {"conspiracys", "conspiracies"},
            {"constanly", "constantly"},
            {"constarnation", "consternation"},
            {"constatn", "constant"},
            {"constinually", "continually"},
            {"constituant", "constituent"},
            {"constituants", "constituents"},
            {"constituion", "constitution"},
            {"containes", "contains"},
            {"contamporaries", "contemporaries"},
            {"contempory", "contemporary"},
            {"contendor", "contender"},
            {"contian", "contain"},
            {"contians", "contains"},
            {"contibute", "contribute"},
            {"contibuted", "contributed"},
            {"contibutes", "contributes"},
            {"contined", "continued"},
            {"continential", "continental"},
            {"continueing", "continuing"},
            {"contravercial", "controversial"},
            {"contributer", "contributor"},
            {"contributers", "contributors"},
            {"contritutions", "contributions"},
            {"controll", "control"},
            {"controlls", "controls"},
            {"controvercy", "controversy"},
            {"controversey", "controversy"},
            {"controvertial", "controversial"},
            {"controvery", "controversy"},
            {"conveinent", "convenient"},
            {"convenant", "covenant"},
            {"conveniance", "convenience"},
            {"convential", "conventional"},
            {"convertion", "conversion"},
            {"coorperation", "cooperation, corporation"},
            {"coorperations", "corporations"},
            {"copmetitors", "competitors"},
            {"coputer", "computer"},
            {"copywrite", "copyright"},
            {"coridal", "cordial"},
            {"cornmitted", "committed"},
            {"corparate", "corporate"},
            {"corperations", "corporations"},
            {"correcters", "correctors"},
            {"correspondant", "correspondent"},
            {"correspondants", "correspondents"},
            {"corrispondant", "correspondent"},
            {"corrispondants", "correspondents"},
            {"coudl", "could, cloud"},
            {"councellor", "councillor, counselor, councilor"},
            {"councellors", "councillors, counselors, councilors"},
            {"countains", "contains"},
            {"countires", "countries"},
            {"coururier", "courier, couturier"},
            {"coverted", "converted, covered, coveted"},
            {"cpoy", "coy, copy"},
            {"creche", "crèche"},
            {"criterias", "criteria"},
            {"criticists", "critics"},
            {"critising", "criticizing"},
            {"critisising", "criticising"},
            {"critisize", "criticize"},
            {"critisized", "criticized"},
            {"critisizes", "criticizes"},
            {"critisizing", "criticizing"},
            {"critized", "criticized"},
            {"critizing", "criticizing"},
            {"crowm", "crown"},
            {"crusies", "cruises"},
            {"crystalisation", "crystallisation"},
            {"cumulatative", "cumulative"},
            {"curch", "church"},
            {"curcuit", "circuit"},
            {"cxan", "cyan"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'd') {
        static struct Correction dict[] = {
            {"daed", "dead"},
            {"dael", "deal, dial, dahl"},
            {"dalmation", "dalmatian"},
            {"dardenelles", "dardanelles"},
            {"decendant", "descendant"},
            {"decendants", "descendants"},
            {"decendent", "descendant"},
            {"decendents", "descendants"},
            {"decomposit", "decompose"},
            {"decomposited", "decomposed"},
            {"decompositing", "decomposing"},
            {"decomposits", "decomposes"},
            {"decress", "decrees"},
            {"decribing", "describing"},
            {"defendent", "defendant"},
            {"defendents", "defendants"},
            {"definance", "defiance"},
            {"definate", "definite"},
            {"definately", "definitely"},
            {"definatly", "definitely"},
            {"definetly", "definitely"},
            {"definining", "defining"},
            {"definit", "definite"},
            {"degrate", "degrade"},
            {"delagates", "delegates"},
            {"delapidated", "dilapidated"},
            {"delevopment", "development"},
            {"deliberatly", "deliberately"},
            {"delusionally", "delusively"},
            {"demographical", "demographic"},
            {"demolision", "demolition"},
            {"denegrating", "denigrating"},
            {"dependance", "dependence"},
            {"deram", "dram, dream"},
            {"deriviated", "derived"},
            {"descision", "decision"},
            {"descisions", "decisions"},
            {"descripters", "descriptors"},
            {"deside", "decide"},
            {"desigining", "designing"},
            {"desintegrated", "disintegrated"},
            {"desintegration", "disintegration"},
            {"desorder", "disorder"},
            {"desoriented", "disoriented"},
            {"desparate", "desperate, disparate"},
            {"despict", "depict"},
            {"despiration", "desperation"},
            {"dessicated", "desiccated"},
            {"dessigned", "designed"},
            {"destory", "destroy"},
            {"detailled", "detailed"},
            {"deteriate", "deteriorate"},
            {"determinining", "determining"},
            {"devasted", "devastated"},
            {"develope", "develop"},
            {"devels", "delves"},
            {"devestating", "devastating"},
            {"devide", "divide"},
            {"devided", "divided"},
            {"devistating", "devastating"},
            {"diamons", "diamonds"},
            {"diaster", "disaster"},
            {"dicovered", "discovered"},
            {"dicovering", "discovering"},
            {"dicovers", "discovers"},
            {"dictionarys", "dictionaries"},
            {"didnt", "didn't"},
            {"diea", "idea, die"},
            {"dieing", "dying, dyeing"},
            {"dieties", "deities"},
            {"diety", "deity"},
            {"differentiatiations", "differentiations"},
            {"difficulity", "difficulty"},
            {"dilema", "dilemma"},
            {"dimention", "dimension"},
            {"dimentions", "dimensions"},
            {"dirived", "derived"},
            {"discontentment", "discontent"},
            {"discribe", "describe"},
            {"discribed", "described"},
            {"discribes", "describes"},
            {"discribing", "describing"},
            {"disenchanged", "disenchanted"},
            {"disobediant", "disobedient"},
            {"disover", "discover"},
            {"dispair", "despair"},
            {"disparingly", "disparagingly"},
            {"dispence", "dispense"},
            {"dispenced", "dispensed"},
            {"dispencing", "dispensing"},
            {"dispicable", "despicable"},
            {"dispite", "despite"},
            {"disproportiate", "disproportionate"},
            {"disputandem", "disputandum"},
            {"dissapeared", "disappeared"},
            {"dissobediant", "disobedient"},
            {"distrubution", "distribution"},
            {"distruction", "destruction"},
            {"distructive", "destructive"},
            {"diversed", "diverse, diverged"},
            {"divice", "device"},
            {"divison", "division"},
            {"doens", "does"},
            {"doesnt", "doesn't"},
            {"doign", "doing"},
            {"dominent", "dominant"},
            {"donig", "doing"},
            {"doub", "doubt, daub, dub"},
            {"dreasm", "dreams"},
            {"driectly", "directly"},
            {"drummless", "drumless"},
            {"dum", "dumb"},
            {"durig", "during"},
            {"duting", "during"},
            {"dyas", "dryas"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'e') {
        static struct Correction dict[] = {
            {"eahc", "each"},
            {"earlies", "earliest"},
            {"earnt", "earned"},
            {"ecclectic", "eclectic"},
            {"ecidious", "deciduous"},
            {"eclispe", "eclipse"},
            {"ecomonic", "economic"},
            {"econoımic", "economic"},
            {"ect", "etc"},
            {"eearly", "early"},
            {"efel", "evil"},
            {"effeciently", "efficiently"},
            {"efford", "effort, afford"},
            {"effords", "efforts, affords"},
            {"eigth", "eighth, eight"},
            {"electic", "eclectic, electric"},
            {"electon", "election, electron"},
            {"electricly", "electrically"},
            {"elementay", "elementary"},
            {"eleminating", "eliminating"},
            {"eles", "eels"},
            {"elicided", "elicited"},
            {"embargos", "embargoes"},
            {"embarras", "embarrass"},
            {"embezelled", "embezzled"},
            {"eminate", "emanate"},
            {"eminated", "emanated"},
            {"emition", "emission, emotion"},
            {"emmediately", "immediately"},
            {"emmigrated", "emigrated, immigrated"},
            {"emminent", "eminent, imminent"},
            {"emmisions", "emissions"},
            {"emmiting", "emitting"},
            {"emmitting", "emitting"},
            {"empirial", "empirical, imperial"},
            {"emporer", "emperor"},
            {"emprisoned", "imprisoned"},
            {"enameld", "enameled"},
            {"enchancement", "enhancement"},
            {"endolithes", "endoliths"},
            {"enduce", "induce"},
            {"ened", "need"},
            {"ensconsed", "ensconced"},
            {"enteratinment", "entertainment"},
            {"entitlied", "entitled"},
            {"enxt", "next"},
            {"equitorial", "equatorial"},
            {"equivelant", "equivalent"},
            {"equivelent", "equivalent"},
            {"equivilant", "equivalent"},
            {"equivilent", "equivalent"},
            {"erally", "orally, really"},
            {"eraticly", "erratically"},
            {"erested", "arrested, erected"},
            {"esle", "else"},
            {"ethose", "those, ethos"},
            {"eventhough", "even though"},
            {"everytime", "every time"},
            {"eveyr", "every"},
            {"evidentally", "evidently"},
            {"examinated", "examined"},
            {"exapansion", "expansion"},
            {"excecuted", "executed"},
            {"excecutes", "executes"},
            {"excecuting", "executing"},
            {"excecution", "execution"},
            {"excedded", "exceeded"},
            {"excede", "exceed"},
            {"excell", "excel"},
            {"excells", "excels"},
            {"excisted", "existed"},
            {"exelent", "excellent"},
            {"exept", "except"},
            {"exerbate", "exacerbate"},
            {"exerbated", "exacerbated"},
            {"exerciese", "exercises"},
            {"exerpts", "excerpts"},
            {"exersize", "exercise"},
            {"exerternal", "external"},
            {"exhalted", "exalted"},
            {"exhilirate", "exhilarate"},
            {"exicting", "exciting"},
            {"existant", "existent"},
            {"expatriot", "expatriate"},
            {"expeced", "expected"},
            {"expecially", "especially"},
            {"expell", "expel"},
            {"expells", "expels"},
            {"experiance", "experience"},
            {"expiditions", "expeditions"},
            {"exploititive", "exploitative"},
            {"extasy", "ecstasy"},
            {"extacy", "ecstasy"},
            {"extention", "extension"},
            {"extentions", "extensions"},
            {"extered", "exerted"},
            {"extint", "extinct, extant"},
            {"extravagent", "extravagant"},
            {"extrem", "extreme"},
            {"extrememly", "extremely"},
            {"extremeophile", "extremophile"},
            {"eyar", "year, eyas"},
            {"eyars", "years, eyas"},
            {"eyasr", "years, eyas"},
            {NULL, NULL}
            // check
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'f') {
        static struct Correction dict[] = {
            {"facilites", "facilities"},
            {"familes", "families"},
            {"familier", "familiar"},
            {"famoust", "famous"},
            {"farenheit", "Fahrenheit"},
            {"fatc", "fact"},
            {"favoutrable", "favourable"},
            {"feromone", "pheromone"},
            {"fertily", "fertility"},
            {"fictious", "fictitious"},
            {"fidn", "find"},
            {"fiel", "feel, field, file, phial"},
            {"fiels", "feels, fields, files, phials"},
            {"fightings", "fighting"},
            {"fimilies", "families"},
            {"firends", "friends"},
            {"firey", "fiery, firry"},
            {"firts", "flirts, first"},
            {"flawess", "flawless"},
            {"fleed", "fled, freed"},
            {"florescent", "fluorescent"},
            {"flourescent", "fluorescent"},
            {"flourishment", "flourishing"},
            {"fomr", "from, form"},
            {"fonetic", "phonetic"},
            {"fontrier", "fontier"},
            {"forbad", "forbade"},
            {"foreward", "foreword"},
            {"forfiet", "forfeit"},
            {"formelly", "formerly"},
            {"formidible", "formidable"},
            {"forunner", "forerunner"},
            {"foucs", "focus"},
            {"foudn", "found"},
            {"fougth", "fought"},
            {"fourties", "forties"},
            {"frome", "from"},
            {"fromed", "formed"},
            {"froniter", "frontier"},
            {"fucntion", "function"},
            {"fucntioning", "functioning"},
            {"funguses", "fungi"},
            {"futhroc", "futhark, futhorc"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'g') {
        static struct Correction dict[] = {
            {"gae", "game, gale"},
            {"gallaxies", "galaxies"},
            {"galvinized", "galvanized"},
            {"ganerate", "generate"},
            {"ganes", "games"},
            {"ganster", "gangster"},
            {"garantee", "guarantee"},
            {"garanteed", "guaranteed"},
            {"garantees", "guarantees"},
            {"gardai", "gardaí"},
            {"gauarana", "guaraná"},
            {"gauranteed", "guaranteed"},
            {"gaurantees", "guarantees"},
            {"gaurd", "guard, gourd"},
            {"gaurentee", "guarantee"},
            {"gaurenteed", "guaranteed"},
            {"gaurentees", "guarantees"},
            {"geneologies", "genealogies"},
            {"geometrician", "geometer"},
            {"geometricians", "geometers"},
            {"gerat", "great"},
            {"glamourous", "glamorous"},
            {"glight", "flight"},
            {"gogin", "going, Gauguin"},
            {"goign", "going"},
            {"gonig", "going"},
            {"gouvener", "governor"},
            {"governer", "governor"},
            {"graet", "great"},
            {"grammer", "gammar"},
            {"grammer", "grammar"},
            {"grat", "great"},
            {"greatful", "grateful"},
            {"gropu", "group"},
            {"grwo", "grow"},
            {"guage", "gauge"},
            {"guidence", "guidance"},
            {"gunanine", "guanine"},
            {"gya", "gay"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'h') {
        static struct Correction dict[] = {
            {"habaeus", "habeas"},
            {"habeus", "habeas"},
            {"haemorrage", "haemorrhage"},
            {"haev", "have, heave"},
            {"halarious", "hilarious"},
            {"halp", "help"},
            {"harras", "harass"},
            {"harrassed", "harassed"},
            {"harrasses", "harassed"},
            {"haviest", "heaviest"},
            {"healthercare", "healthcare"},
            {"heared", "heard"},
            {"heathy", "healthy"},
            {"heigher", "higher"},
            {"heirarchy", "hierarchy"},
            {"heiroglyphics", "hieroglyphics"},
            {"helment", "helmet"},
            {"herad", "heard, Hera"},
            {"heroe", "hero"},
            {"heros", "heroes"},
            {"hertiage", "heritage"},
            {"hertzs", "hertz"},
            {"hieght", "height"},
            {"hierarcy", "hierarchy"},
            {"hismelf", "himself"},
            {"hitsingles", "hit singles"},
            {"holf", "hold"},
            {"homestate", "home state"},
            {"honory", "honorary"},
            {"hosited", "hoisted"},
            {"housr", "hours, house"},
            {"hten", "then, hen, the"},
            {"htere", "there, here"},
            {"htey", "they"},
            {"htikn", "think"},
            {"hting", "thing"},
            {"htink", "think"},
            {"htis", "this"},
            {"humer", "humor, humour"},
            {"humerous", "humorous, humerus"},
            {"humourous", "humorous"},
            {"humurous", "humorous"},
            {"husban", "husband"},
            {"hvae", "have"},
            {"hvaing", "having"},
            {"hvea", "have, heave"},
            {"hwihc", "which"},
            {"hwile", "while"},
            {"hwole", "whole"},
            {"hydropile", "hydrophile"},
            {"hydropobe", "hydrophobe"},
            {"hypocracy", "hypocrisy"},
            {"hypocrit", "hypocrite"},
            {"hypocrits", "hypocrites"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'i') {
        static struct Correction dict[] = {
            {"idaeidae", "idea"},
            {"idaes", "ideas"},
            {"idealogies", "ideologies"},
            {"idealogy", "ideology"},
            {"ideosyncratic", "idiosyncratic"},
            {"idesa", "ideas, ides"},
            {"illegimacy", "illegitimacy"},
            {"imagin", "imagine"},
            {"imaginery", "imaginary, imagery"},
            {"imanent", "eminent, imminent"},
            {"imigrant", "emigrant, immigrant"},
            {"imigrated", "emigrated, immigrated"},
            {"imigration", "emigration, immigration"},
            {"iminent", "eminent, imminent, immanent"},
            {"immediatley", "immediately"},
            {"immediatly", "immediately"},
            {"immidiately", "immediately"},
            {"immitate", "imitate"},
            {"immitated", "imitated"},
            {"immitating", "imitating"},
            {"immitator", "imitator"},
            {"impedence", "impedance"},
            {"impliment", "implement"},
            {"implimented", "implemented"},
            {"imploys", "employs"},
            {"improvision", "improvisation"},
            {"inadvertant", "inadvertent"},
            {"inaugures", "inaugurates"},
            {"inbalance", "imbalance"},
            {"inbalanced", "imbalanced"},
            {"inbetween", "between"},
            {"incarcirated", "incarcerated"},
            {"incidentially", "incidentally"},
            {"incidently", "incidentally"},
            {"includ", "include"},
            {"incompatabilities", "incompatibilities"},
            {"incompatability", "incompatibility"},
            {"incompatable", "incompatible"},
            {"incompatablities", "incompatibilities"},
            {"incompatablity", "incompatibility"},
            {"incompetant", "incompetent"},
            {"inconsistant", "inconsistent"},
            {"incorperation", "incorporation"},
            {"incredable", "incredible"},
            {"indefineable", "undefinable"},
            {"indentical", "identical"},
            {"independant", "independent"},
            {"indespensable", "indispensable"},
            {"indespensible", "indispensable"},
            {"indipendent", "independent"},
            {"indispensible", "indispensable"},
            {"indite", "indict"},
            {"indulgue", "indulge"},
            {"inefficienty", "inefficiently"},
            {"inevatible", "inevitable"},
            {"inevitible", "inevitable"},
            {"inevititably", "inevitably"},
            {"infalability", "infallibility"},
            {"infallable", "infallible"},
            {"infinit", "infinite"},
            {"influented", "influenced"},
            {"inhabitans", "inhabitants"},
            {"inheritage", "heritage, inheritance"},
            {"inital", "initial"},
            {"inlcuding", "including"},
            {"inmigrants", "immigrants"},
            {"innoculated", "inoculated"},
            {"inofficial", "unofficial"},
            {"inot", "into"},
            {"inpending", "impending"},
            {"inpenetrable", "impenetrable"},
            {"inpolite", "impolite"},
            {"inproving", "improving"},
            {"insensative", "insensitive"},
            {"inseperable", "inseparable"},
            {"inspite", "in spite, inspire"},
            {"instade", "instead"},
            {"instatance", "instance"},
            {"institue", "institute"},
            {"instutionalized", "institutionalized"},
            {"instutions", "institutions, intuitions"},
            {"insurence", "insurance"},
            {"intented", "intended, indented"},
            {"intepretator", "interpretor"},
            {"interational", "international"},
            {"interbread", "interbreed, interbred"},
            {"intercontinential", "intercontinental"},
            {"intered", "interred, interned"},
            {"interferance", "interference"},
            {"interfereing", "interfering"},
            {"intergrated", "integrated"},
            {"intergration", "integration"},
            {"interm", "interim"},
            {"internation", "international"},
            {"intertaining", "entertaining"},
            {"intervines", "intervenes"},
            {"introdued", "introduced"},
            {"intruduced", "introduced"},
            {"intrument", "instrument"},
            {"intrumental", "instrumental"},
            {"intruments", "instruments"},
            {"intrusted", "entrusted"},
            {"inumerable", "enumerable, innumerable"},
            {"inventer", "inventor"},
            {"irelevent", "irrelevant"},
            {"ironicly", "ironically"},
            {"irregardless", "regardless"},
            {"irrelevent", "irrelevant"},
            {"iunior", "junior"},
            {"iwll", "will"},
            {"iwth", "with"},
            {NULL, NULL}
            // check
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'j') {
        static struct Correction dict[] = {
            {"journied", "journeyed"},
            {"journies", "journeys"},
            {"jstu", "just"},
            {"jsut", "just"},
            {NULL, NULL}
            // check
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'k') {
        static struct Correction dict[] = {
            {"klenex", "kleenex"},
            {"knifes", "knives"},
            {"knwo", "know"},
            {"knwos", "knows"},
            {"konw", "know"},
            {"konws", "knows"},
            {"kwno", "know"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'l') {
        static struct Correction dict[] = {
            {"labatory", "lavatory, laboratory"},
            {"lable", "label"},
            {"labled", "labelled, labeled"},
            {"larg", "large"},
            {"larrry", "larry"},
            {"lastr", "last"},
            {"launchs", "launch, launches"},
            {"layed", "laid"},
            {"leage", "league"},
            {"leanr", "lean, learn, leaner"},
            {"lefted", "left"},
            {"leibnitz", "leibniz"},
            {"lenght", "length"},
            {"leran", "learn"},
            {"lerans", "learns"},
            {"lesbain", "lesbian"},
            {"lesbina", "lesbian"},
            {"levetating", "levitating"},
            {"levle", "level"},
            {"liad", "laid"},
            {"liasion", "liaison"},
            {"liason", "liaison"},
            {"libell", "libel"},
            {"libguistic", "linguistic"},
            {"libitarianisn", "libertarianism"},
            {"lible", "libel, liable"},
            {"lieing", "lying"},
            {"liek", "like"},
            {"liekd", "liked"},
            {"liesure", "leisure"},
            {"lightyear", "light year"},
            {"lightyears", "light years"},
            {"linnaena", "linnaean"},
            {"lippizaner", "lipizzaner"},
            {"liquify", "liquefy"},
            {"liscense", "license, licence"},
            {"lisence", "license, licence"},
            {"lisense", "license, licence"},
            {"litature", "literature"},
            {"littel", "little"},
            {"livley", "lively"},
            {"loev", "love"},
            {"lonley", "lonely"},
            {"lonly", "lonely, only"},
            {"loosing", "losing"},
            {"lotharingen", "lothringen"},
            {"lsat", "last"},
            {"lukid", "likud"},
            {"lveo", "love"},
            {"lvoe", "love"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'm') {
        static struct Correction dict[] = {
            {"maching", "machine, marching, matching"},
            {"mackeral", "mackerel"},
            {"magincian", "magician"},
            {"maintance", "maintenance"},
            {"maintinaing", "maintaining"},
            {"maintioned", "mentioned"},
            {"majoroty", "majority"},
            {"maked", "marked, made"},
            {"makse", "makes"},
            {"maltesian", "Maltese"},
            {"managable", "manageable, manageably"},
            {"manouver", "maneuver, manoeuvre"},
            {"manouverability", "maneuverability, manoeuvrability, manoeuverability"},
            {"manouverable", "maneuverable, manoeuvrable"},
            {"manouvers", "maneuvers, manoeuvres"},
            {"manuever", "maneuver, manoeuvre"},
            {"manuevers", "maneuvers, manoeuvres"},
            {"markes", "marks"},
            {"massmedia", "mass media"},
            {"mataphysical", "metaphysical"},
            {"materalists", "materialist"},
            {"mathematicas", "mathematics"},
            {"matheticians", "mathematicians"},
            {"mccarthyst", "mccarthyist"},
            {"mear", "wear, mere, mare"},
            {"medeival", "medieval"},
            {"mediciney", "mediciny"},
            {"medievel", "medieval"},
            {"membranaphone", "membranophone"},
            {"menally", "mentally"},
            {"meranda", "veranda, Miranda"},
            {"metalurgic", "metallurgic"},
            {"midwifes", "midwives"},
            {"miliary", "military"},
            {"miliraty", "military"},
            {"millitary", "military"},
            {"minerial", "mineral"},
            {"ministery", "ministry"},
            {"mischievous", "mischievous"},
            {"missen", "mizzen"},
            {"misterious", "mysterious"},
            {"mistery", "mystery"},
            {"misteryous", "mysterious"},
            {"mkae", "make"},
            {"mkaes", "makes"},
            {"mkaing", "making"},
            {"mkea", "make"},
            {"moderm", "modem"},
            {"modle", "model"},
            {"moeny", "money"},
            {"momento", "memento"},
            {"monestaries", "monasteries"},
            {"monestary", "monastery, monetary"},
            {"monickers", "monikers"},
            {"monolite", "monolithic"},
            {"montains", "mountains"},
            {"montanous", "mountainous"},
            {"monts", "months"},
            {"moreso", "more, more so"},
            {"morroccan", "moroccan"},
            {"mounth", "month"},
            {"movei", "movie"},
            {"mroe", "more"},
            {"mucuous", "mucous"},
            {"muder", "murder"},
            {"mudering", "murdering"},
            {"multipled", "multiplied"},
            {"munbers", "numbers"},
            {"muscels", "mussels, muscles"},
            {"myraid", "myriad"},
            {"mysef", "myself"},
            {"mysogynist", "misogynist"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'n') {
        static struct Correction dict[] = {
            {"naturely", "naturally"},
            {"naturually", "naturally"},
            {"neglible", "negligible"},
            {"negligable", "negligible"},
            {"neice", "niece, nice"},
            {"neigbour", "neighbour, neighbor"},
            {"neigbourhood", "neighbourhood"},
            {"neigbouring", "neighbouring, neighboring"},
            {"neigbours", "neighbours, neighbors"},
            {"neolitic", "neolithic"},
            {"nestin", "nesting"},
            {"nickle", "nickel"},
            {"nieghbor", "neighbor"},
            {"ninties", "1990s"},
            {"nkow", "know"},
            {"nkwo", "know"},
            {"nmae", "name"},
            {"noncombatents", "noncombatants"},
            {"nonsence", "nonsense"},
            {"noone", "no one"},
            {"northen", "northern"},
            {"notabley", "notably"},
            {"noticeing", "noticing"},
            {"noticible", "noticeable"},
            {"nowdays", "nowadays"},
            {"nowe", "now"},
            {"nto", "not"},
            {"nucular", "nuclear"},
            {"nutritent", "nutrient"},
            {"nuturing", "nurturing"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'o') {
        static struct Correction dict[] = {
            {"obediance", "obedience"},
            {"obediant", "obedient"},
            {"obstacal", "obstacle"},
            {"obstruced", "obstructed"},
            {"ocassion", "occasion"},
            {"occassion", "occasion"},
            {"occurr", "occur"},
            {"ocuntries", "countries"},
            {"ocuntry", "country"},
            {"ocurr", "occur"},
            {"oftenly", "often"},
            {"oging", "going, ogling"},
            {"olther", "other"},
            {"ommiting", "omitting"},
            {"omniverous", "omnivorous"},
            {"omre", "more"},
            {"onot", "note, not"},
            {"onyl", "only"},
            {"opponant", "opponent"},
            {"opthamologist", "ophthalmologist"},
            {"orded", "ordered"},
            {"organim", "organism"},
            {"orgin", "origin, organ"},
            {"orginize", "organise"},
            {"originall", "original, originally"},
            {"otehr", "other "},
            {"oublisher", "publisher"},
            {"ouevre", "oeuvre"},
            {"overthere", "over there"},
            {"owrk", "work"},
            {"owudl", "would"},
            {NULL, NULL}
            // check
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'p') {
        static struct Correction dict[] = {
            {"paide", "paid"},
            {"palce", "place, palace"},
            {"paleolitic", "paleolithic"},
            {"pallete", "palette"},
            {"pantomine", "pantomime"},
            {"paralel", "parallel"},
            {"paralell", "parallel"},
            {"paralelly", "parallelly"},
            {"paralely", "parallelly"},
            {"parallely", "parallelly"},
            {"paranthesis", "parenthesis"},
            {"parisitic", "parasitic"},
            {"parrakeets", "parakeets"},
            {"parrallell", "parallel"},
            {"parrallelly", "parallelly"},
            {"parrallely", "parallelly"},
            {"particually", "particularly"},
            {"particulary", "particularly"},
            {"particuly", "particularly"},
            {"pary", "party, parry"},
            {"passerbys", "passersby"},
            {"pastural", "pastoral"},
            {"pattented", "patented"},
            {"payed", "paid"},
            {"peacefuland", "peaceful and"},
            {"peageant", "pageant"},
            {"peaples", "peoples"},
            {"peculure", "peculiar"},
            {"pedestrain", "pedestrian"},
            {"peice", "piece"},
            {"penatly", "penalty"},
            {"penerator", "penetrator"},
            {"pensle", "pencil"},
            {"peom", "poem"},
            {"peoms", "poems"},
            {"peopel", "people"},
            {"peopels", "peoples"},
            {"peotry", "poetry"},
            {"perade", "parade"},
            {"percepted", "perceived"},
            {"performence", "performance"},
            {"performes", "performed, performs"},
            {"perhasp", "perhaps"},
            {"perhpas", "perhaps"},
            {"perjery", "perjury"},
            {"perjorative", "pejorative"},
            {"permanant", "permanent"},
            {"permenant", "permanent"},
            {"permenantly", "permanently"},
            {"permissable", "permissible"},
            {"perogative", "prerogative"},
            {"perosnality", "personality"},
            {"perphas", "perhaps"},
            {"personel", "personnel, personal"},
            {"personell", "personnel"},
            {"personnell", "personnel"},
            {"persue", "pursue"},
            {"persued", "pursued"},
            {"persuing", "pursuing"},
            {"persuits", "pursuits"},
            {"phylosophical", "philosophical"},
            {"pinoneered", "pioneered"},
            {"planed", "planned"},
            {"plateu", "plateau"},
            {"playwrite", "playwright"},
            {"playwrites", "playwrights"},
            {"pleasent", "pleasant"},
            {"poenis", "penis"},
            {"poeoples", "peoples"},
            {"poety", "poetry"},
            {"poisin", "poison"},
            {"polical", "political"},
            {"polysaccharid", "polysaccharide"},
            {"pomotion", "promotion"},
            {"poportional", "proportional"},
            {"populare", "popular"},
            {"populer", "popular"},
            {"porshan", "portion"},
            {"porshon", "portion"},
            {"portuguease", "portuguese"},
            {"portugues", "Portuguese"},
            {"posion", "poison"},
            {"positon", "position, positron"},
            {"possessess", "possesses"},
            {"possition", "position"},
            {"potatos", "potatoes"},
            {"poverful", "powerful"},
            {"practial", "practical"},
            {"practicly", "practically"},
            {"practioners", "practitioners"},
            {"prairy", "prairie"},
            {"preample", "preamble"},
            {"preceed", "precede"},
            {"preceeded", "preceded"},
            {"preceeding", "preceding"},
            {"preceeds", "precedes"},
            {"precentage", "percentage"},
            {"precice", "precise"},
            {"precurser", "precursor"},
            {"predicatble", "predictable"},
            {"predicitons", "predictions"},
            {"predomiantly", "predominately"},
            {"preiod", "period"},
            {"preliferation", "proliferation"},
            {"premeire", "premiere"},
            {"premission", "permission"},
            {"prepair", "prepare"},
            {"prepatory", "preparatory"},
            {"preperation", "preparation"},
            {"preperations", "preparations"},
            {"preriod", "period"},
            {"presense", "presence"},
            {"presidenital", "presidential"},
            {"presidental", "presidential"},
            {"prespective", "perspective"},
            {"prestigeous", "prestigious"},
            {"presumabely", "presumably"},
            {"pretection", "protection"},
            {"prevelant", "prevalent"},
            {"preverse", "perverse"},
            {"previvous", "previous"},
            {"primarly", "primarily"},
            {"primative", "primitive"},
            {"primatively", "primitively"},
            {"primordal", "primordial"},
            {"principaly", "principality"},
            {"principial", "principal"},
            {"principly", "principally"},
            {"privilage", "privilege"},
            {"probabilaty", "probability"},
            {"probablly", "probably"},
            {"probalibity", "probability"},
            {"probaly", "probably"},
            {"procede", "proceed, precede"},
            {"proceded", "proceeded, preceded"},
            {"procedes", "proceeds, precedes"},
            {"procedger", "procedure"},
            {"proceding", "proceeding, preceding"},
            {"proces", "process"},
            {"processer", "processor"},
            {"proclomation", "proclamation"},
            {"profesion", "profusion, profession"},
            {"professer", "professor"},
            {"profilic", "prolific"},
            {"progidy", "prodigy"},
            {"progrom", "pogrom, program"},
            {"progroms", "pogroms, programs"},
            {"prohabition", "prohibition"},
            {"prominant", "prominent"},
            {"prominantly", "prominently"},
            {"prominately", "prominently, predominately"},
            {"promotted", "promoted"},
            {"pronomial", "pronominal"},
            {"prophacy", "prophecy"},
            {"propogate", "propagate"},
            {"propogates", "propagates"},
            {"propogation", "propagation"},
            {"propper", "proper"},
            {"proprietory", "proprietary"},
            {"proseletyzing", "proselytizing"},
            {"protaganist", "protagonist"},
            {"protaganists", "protagonists"},
            {"protocal", "protocol"},
            {"protoganist", "protagonist"},
            {"protrayed", "portrayed"},
            {"prouncements", "pronouncements"},
            {"provacative", "provocative"},
            {"provisiosn", "provision"},
            {"pseudononymous", "pseudonymous"},
            {"publicaly", "publicly"},
            {"publisherr", "publisher"},
            {"publishre", "publisher"},
            {"puchasing", "purchasing"},
            {"purposedly", "purposely"},
            {"pursuade", "persuade"},
            {"pursuades", "persuades"},
            {"pususading", "persuading"},
            {"pwoer", "power"},
            {"pyscic", "psychic"},
            {NULL, NULL}
            // checked
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'q') {
        static struct Correction dict[] = {
            {"qtuie", "quite, quiet"},
            {"quantaty", "quantity"},
            {"quantitiy", "quantity"},
            {"quicklyu", "quickly"},
            {"quitted", "quit"},
            {"quize", "quiz"},
            {"qutie", "quite, quiet"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'r') {
        static struct Correction dict[] = {
            {"radify", "ratify"},
            {"raelly", "really"},
            {"rarified", "rarefied"},
            {"reaccurring", "recurring"},
            {"readmition", "readmission"},
            {"realitvely", "relatively"},
            {"realtions", "relations"},
            {"realyl", "really"},
            {"rebounce", "rebound"},
            {"receeding", "receding"},
            {"receivedfrom", "received from"},
            {"recepient", "recipient"},
            {"recepients", "recipients"},
            {"reched", "reached"},
            {"recide", "reside"},
            {"recided", "resided"},
            {"recident", "resident"},
            {"recidents", "residents"},
            {"reciding", "residing"},
            {"recipiant", "recipient"},
            {"recipiants", "recipients"},
            {"recipt", "receipt"},
            {"recompence", "recompense"},
            {"reconcilation", "reconciliation"},
            {"recordproducer", "record producer"},
            {"recquired", "required"},
            {"recrod", "record"},
            {"rediculous", "ridiculous"},
            {"reedeming", "redeeming"},
            {"reenforced", "reinforced"},
            {"refect", "reflect"},
            {"referece", "reference"},
            {"referemces", "references"},
            {"referencs", "references"},
            {"referiang", "referring"},
            {"refering", "referring"},
            {"refernce", "reference, references"},
            {"referrs", "refers"},
            {"reffered", "referred"},
            {"reffering", "referring"},
            {"refusla", "refusal"},
            {"regardes", "regards"},
            {"reigining", "reigning"},
            {"reknowned", "renowned"},
            {"rela", "real"},
            {"relavant", "relevant"},
            {"relavent", "relevant"},
            {"relected", "reelected"},
            {"releive", "relieve"},
            {"releived", "relieved"},
            {"relevent", "relevant"},
            {"relient", "reliant"},
            {"relized", "realised, realized"},
            {"relpacement", "replacement"},
            {"remaing", "remaining"},
            {"rememberable", "memorable"},
            {"remembrence", "remembrance"},
            {"reminent", "remnant"},
            {"renedered", "rende"},
            {"renewl", "renewal"},
            {"rennovate", "renovate"},
            {"rentors", "renters"},
            {"reoccurrence", "recurrence"},
            {"reorganision", "reorganisation"},
            {"repatition", "repetition, repartition"},
            {"repectively", "respectively"},
            {"repentent", "repentant"},
            {"repeteadly", "repeatedly"},
            {"repetion", "repetition"},
            {"repid", "rapid"},
            {"reponsible", "responsible"},
            {"reportadly", "reportedly"},
            {"representive", "representative"},
            {"representives", "representatives"},
            {"repsectively", "respectively"},
            {"republi", "republic"},
            {"republian", "republican"},
            {"republis", "republics"},
            {"resemblence", "resemblance"},
            {"resignement", "resignment"},
            {"resistable", "resistible"},
            {"resistence", "resistance"},
            {"resistent", "resistant"},
            {"responce", "response"},
            {"responsability", "responsibility"},
            {"responsibilites", "responsibilities"},
            {"ressemble", "resemble"},
            {"restaraunt", "restaurant"},
            {"restaraunts", "restaurants"},
            {"restauration", "restoration"},
            {"resteraunt", "restaurant"},
            {"resteraunts", "restaurants"},
            {"restraunt", "restraint, restaurant"},
            {"resturaunts", "restaurants"},
            {"retreive", "retrieve"},
            {"returnd", "returned"},
            {"revaluated", "reevaluated"},
            {"reveral", "reversal"},
            {"reversable", "reversible"},
            {"revolutionar", "revolutionary"},
            {"rewriet", "rewrite"},
            {"rigeur", "rigueur, rigour, rigor"},
            {"rigourous", "rigorous"},
            {"rininging", "ringing"},
            {"rised", "raised, rose"},
            {"rucuperate", "recuperate"},
            {"russina", "Russian"},
            {"rwite", "write"},
            {"rythem", "rhythm"},
            {"rythim", "rhythm"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 's') {
        static struct Correction dict[] = {
            {"sacrifical", "sacrificial"},
            {"sargant", "sergeant"},
            {"sargeant", "sergeant"},
            {"sargent", "sergeant"},
            {"sasy", "says, sassy"},
            {"saveing", "saving"},
            {"scaleable", "scalable"},
            {"scandanavia", "Scandinavia"},
            {"schedual", "schedule"},
            {"scholarstic", "scholastic, scholarly"},
            {"scientis", "scientist"},
            {"scrutinity", "scrutiny"},
            {"secceeded", "seceded, succeeded"},
            {"seceed", "succeed, secede"},
            {"seceeded", "succeeded, seceded"},
            {"secretery", "secretary"},
            {"seeked", "sought"},
            {"seguoys", "segues"},
            {"seige", "siege"},
            {"seinor", "senior"},
            {"seldomly", "seldom"},
            {"senarios", "scenarios"},
            {"sence", "sense, since"},
            {"sensure", "censure"},
            {"seperate", "separate"},
            {"seperates", "separates"},
            {"seperation", "separation"},
            {"sepina", "subpoena"},
            {"sepulchure", "sepulchre, sepulcher"},
            {"sepulcre", "sepulchre, sepulcher"},
            {"serendipiyt", "serendipity"},
            {"sergent", "sergeant"},
            {"severley", "severely"},
            {"severly", "severely"},
            {"shadasloo", "shadaloo"},
            {"shadoloo", "shadaloo"},
            {"shamen", "shaman, shamans"},
            {"sheat", "sheath, sheet, cheat"},
            {"sherif", "sheriff"},
            {"shineing", "shining"},
            {"shorly", "shortly"},
            {"shortwhile", "short while"},
            {"shoudl", "should"},
            {"shouldnt", "should not"},
            {"shreak", "shriek"},
            {"shrinked", "shrunk"},
            {"sicne", "since"},
            {"sieze", "seize, size"},
            {"siezed", "seized, sized"},
            {"siezing", "seizing, sizing"},
            {"siezure", "seizure"},
            {"siezures", "seizures"},
            {"signitories", "signatories"},
            {"simpley", "simply"},
            {"simplier", "simpler"},
            {"sinse", "sines, since"},
            {"slippy", "slippery"},
            {"slowy", "slowly"},
            {"smae", "same"},
            {"smoe", "some"},
            {"sneeks", "sneaks"},
            {"soem", "some"},
            {"sohw", "show"},
            {"soilders", "soldiers"},
            {"soley", "solely"},
            {"soliders", "soldiers"},
            {"sophicated", "sophisticated"},
            {"sorrounding", "surrounding"},
            {"sotry", "story"},
            {"sotyr", "satyr, story"},
            {"soudn", "sound"},
            {"soudns", "sounds"},
            {"sould", "could, should, sold, soul"},
            {"souvenier", "souvenir"},
            {"souveniers", "souvenirs"},
            {"spainish", "Spanish"},
            {"speciallized", "specialised, specialized"},
            {"specif", "specific, specify"},
            {"speciman", "specimen"},
            {"spects", "aspects, expects"},
            {"spectum", "spectrum"},
            {"speices", "species"},
            {"spermatozoan", "spermatozoon"},
            {"sponser", "sponsor"},
            {"spreaded", "spread"},
            {"spred", "spread"},
            {"stainlees", "stainless"},
            {"standars", "standards"},
            {"stange", "strange"},
            {"startegies", "strategies"},
            {"stateman", "statesman"},
            {"stilus", "stylus"},
            {"stirrs", "stirs"},
            {"stlye", "style"},
            {"stomache", "stomach"},
            {"storeis", "stories"},
            {"storise", "stories"},
            {"stoyr", "story"},
            {"stpo", "stop"},
            {"stradegies", "strategies"},
            {"strat", "start, strata"},
            {"strenght", "strength"},
            {"strenghten", "strengthen"},
            {"strenuos", "strenuous"},
            {"strictist", "strictest"},
            {"strikely", "strikingly"},
            {"strnad", "strand"},
            {"stroy", "story, destroy"},
            {"structuer", "structure"},
            {"stuctured", "structured"},
            {"studdy", "study"},
            {"studing", "studying"},
            {"stuggling", "struggling"},
            {"subdivisio", "subdivision"},
            {"submachne", "submachine"},
            {"subsiduary", "subsidiary"},
            {"substace", "substance"},
            {"substancial", "substantial"},
            {"substituded", "substituted"},
            {"subterranian", "subterranean"},
            {"suburburban", "suburban"},
            {"sucesfuly", "successfully"},
            {"sucesion", "succession"},
            {"sucessot", "successor"},
            {"sucidial", "suicidal"},
            {"sudent", "student"},
            {"sudents", "students"},
            {"suop", "soup"},
            {"superceeded", "superseded"},
            {"superintendant", "superintendent"},
            {"suphisticated", "sophisticated"},
            {"supposingly", "supposedly"},
            {"suprassing", "surpassing"},
            {"suprised", "surprised"},
            {"suprising", "surprising"},
            {"suprize", "surprise"},
            {"suprized", "surprised"},
            {"suprizing", "surprising"},
            {"surley", "surly, surely"},
            {"surplanted", "supplanted"},
            {"surpress", "suppress"},
            {"surpressed", "suppressed"},
            {"surprize", "surprise"},
            {"surprized", "surprised"},
            {"surprizing", "surprising"},
            {"surrended", "surrounded, surrendered"},
            {"surrundering", "surrendering"},
            {"surveill", "surveil"},
            {"surveyer", "surveyor"},
            {"surviver", "survivor"},
            {"survivers", "survivors"},
            {"survivied", "survived"},
            {"suspention", "suspension"},
            {"swaer", "swear"},
            {"swaers", "swears"},
            {"swepth", "swept"},
            {"syas", "says"},
            {"symmetral", "symmetric"},
            {"synonomous", "synonymous"},
            {"synonymns", "synonyms"},
            {"synphony", "symphony"},
            {"sysmatically", "systematically"},
            {"sytle", "style"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 't') {
        static struct Correction dict[] = {
            {"tahn", "than"},
            {"taht", "that"},
            {"tast", "taste"},
            {"tath", "that"},
            {"tato", "tattoo"},
            {"teached", "taught"},
            {"teh", "the"},
            {"tehy", "they"},
            {"telelevision", "television"},
            {"tendancies", "tendencies"},
            {"tendancy", "tendency"},
            {"tennisplayer", "tennis player"},
            {"territorist", "terrorist"},
            {"tghe", "the"},
            {"theather", "theater"},
            {"theif", "thief"},
            {"themselfs", "themselves"},
            {"ther", "there, their, the"},
            {"theri", "their"},
            {"thgat", "that"},
            {"thge", "the"},
            {"thier", "their"},
            {"thign", "thing"},
            {"thigns", "things"},
            {"thigsn", "things"},
            {"thikn", "think"},
            {"thikning", "thinking, thickening"},
            {"thikns", "thinks"},
            {"thn", "then"},
            {"thna", "than"},
            {"thne", "then"},
            {"threatend", "threatened"},
            {"thrid", "third"},
            {"throughly", "thoroughly"},
            {"throught", "thought, through, throughout"},
            {"thru", "through"},
            {"thsi", "this"},
            {"thsoe", "those"},
            {"thta", "that"},
            {"tiem", "time, Tim"},
            {"tihkn", "think"},
            {"tihs", "this"},
            {"timeschedule", "time schedule"},
            {"timne", "time"},
            {"tiome", "time, tome"},
            {"tje", "the"},
            {"tjhe", "the"},
            {"tjpanishad", "upanishad"},
            {"tkae", "take"},
            {"tkaes", "takes"},
            {"tkaing", "taking"},
            {"tlaking", "talking"},
            {"todya", "today"},
            {"toke", "took"},
            {"tomatos", "tomatoes"},
            {"tormenters", "tormentors"},
            {"tornadoe", "tornado"},
            {"torpeados", "torpedoes"},
            {"torpedos", "torpedoes"},
            {"tothe", "to the"},
            {"toubles", "troubles"},
            {"tounge", "tongue"},
            {"tourch", "torch, touch"},
            {"towrad", "toward"},
            {"tradionally", "traditionally"},
            {"traditionnal", "traditional"},
            {"traditition", "tradition"},
            {"trafficed", "trafficked"},
            {"transcendant", "transcendent"},
            {"transcendentational", "transcendental"},
            {"transcripting", "transcribing, transcription"},
            {"translater", "translator"},
            {"translaters", "translators"},
            {"triology", "trilogy"},
            {"troup", "troupe"},
            {"troups", "troupes, troops"},
            {"turnk", "turnkey, trunk"},
            {"twon", "town"},
            {"twpo", "two"},
            {"tyhe", "they"},
            {"tyrany", "tyranny"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'u') {
        static struct Correction dict[] = {
            {"ublisher", "publisher"},
            {"uise", "use"},
            {"unathorised", "unauthorised"},
            {"unavailible", "unavailable"},
            {"uncertainity", "uncertainty"},
            {"uncompetive", "uncompetitive"},
            {"unconfortability", "discomfort"},
            {"unconvential", "unconventional"},
            {"understoon", "understood"},
            {"unequalities", "inequalities"},
            {"unfortunatley", "unfortunately"},
            {"unilatreal", "unilateral"},
            {"univeral", "universal"},
            {"unmanouverable", "unmaneuverable, unmanoeuvrable"},
            {"unnessary", "unnecessary"},
            {"unoperational", "nonoperational"},
            {"unoticeable", "unnoticeable"},
            {"unplease", "displease"},
            {"unrepentent", "unrepentant"},
            {"unsed", "used, unused, unsaid"},
            {"unsucesfuly", "unsuccessfully"},
            {"unsurprized", "unsurprised"},
            {"untill", "until"},
            {"unweildly", "unwieldy"},
            {"unwieldly", "unwieldy"},
            {"upcomming", "upcoming"},
            {"upto", "up to"},
            {"usally", "usually"},
            {"utill", "until"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'v') {
        static struct Correction dict[] = {
            {"vaccume", "vacuum"},
            {"vacinity", "vicinity"},
            {"vaguaries", "vagaries"},
            {"valetta", "valletta"},
            {"varient", "variant"},
            {"variey", "variety"},
            {"varities", "varieties"},
            {"varity", "variety"},
            {"vehicule", "vehicle"},
            {"vell", "well"},
            {"vermillion", "vermilion"},
            {"versitilaty", "versatility"},
            {"vetween", "between"},
            {"veyr", "very"},
            {"vigeur", "vigueur, vigour, vigor"},
            {"villian", "villain"},
            {"villin", "villi, villain, villein"},
            {"vincinity", "vicinity"},
            {"viscious", "vicious, viscous"},
            {"visting", "visiting"},
            {"vitories", "victories"},
            {"volcanoe", "volcano"},
            {"volumne", "volume"},
            {"vreity", "variety"},
            {"vrey", "very"},
            {"vyer", "very"},
            {"vyre", "very"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'w') {
        static struct Correction dict[] = {
            {"waht", "what"},
            {"warantee", "warranty"},
            {"warrriors", "warriors"},
            {"wass", "was"},
            {"watn", "want"},
            {"wayword", "wayward"},
            {"weas", "was"},
            {"wehn", "when"},
            {"weild", "wield, wild"},
            {"weilded", "wielded"},
            {"wendsay", "Wednesday"},
            {"wensday", "Wednesday"},
            {"wether", "whether, weather"},
            {"whant", "want"},
            {"whants", "wants"},
            {"wheras", "whereas"},
            {"wherease", "whereas"},
            {"whereever", "wherever"},
            {"whic", "which"},
            {"whith", "with"},
            {"whlch", "which"},
            {"whn", "when"},
            {"wholy", "wholly, holy"},
            {"whta", "what"},
            {"whther", "whether"},
            {"wich", "which, witch"},
            {"wief", "wife"},
            {"wiew", "view"},
            {"wiht", "with"},
            {"wille", "will"},
            {"willk", "will"},
            {"wirting", "writing"},
            {"withdrawl", "withdrawal, withdraw"},
            {"withh", "with"},
            {"withing", "within"},
            {"witht", "with"},
            {"witn", "with"},
            {"wnat", "want"},
            {"wnats", "wants"},
            {"wohle", "whole"},
            {"wokr", "work"},
            {"wokring", "working"},
            {"worls", "world"},
            {"woudl", "would"},
            {"wresters", "wrestlers"},
            {"wriet", "write"},
            {"wroet", "wrote"},
            {"wrok", "work"},
            {"wroking", "working"},
            {"wtih", "with"},
            {"wupport", "support"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }

    } else if (miss[0] == 'y') {
        static struct Correction dict[] = {
            {"yaer", "year"},
            {"yaerly", "yearly"},
            {"yaers", "years"},
            {"yatch", "yacht"},
            {"yearm", "year"},
            {"yeasr", "years"},
            {"yeild", "yield"},
            {"yeilding", "yielding"},
            {"yera", "year"},
            {"yeras", "years"},
            {"yersa", "years"},
            {"yotube", "youtube"},
            {"youseff", "yousef"},
            {"yrea", "year"},
            {"yuo", "you"},
            {NULL, NULL}
        };

        for (int i = 0; dict[i].wrong != NULL; i++) {
            if (strcmp(miss, dict[i].wrong) == 0) return dict[i].right;
        }
    }

    return " ";
}
